# Generated by Django 6.0.6 on 2026-06-12 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_hash', models.CharField(db_index=True, max_length=40)),
                ('title', models.CharField(max_length=1024)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('magnet_uri', models.TextField()),
                ('putio_transfer_id', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('sent', 'Sent to put.io'), ('failed', 'Failed')], default='sent', max_length=16)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='download_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
