# Generated by Django 6.0.6 on 2026-06-12 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadrequest',
            name='destination',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
