# Generated by Django 6.0.6 on 2026-09-03 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_downloadrequest_destination'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='downloadrequest',
            options={'ordering': ['-created_at'], 'permissions': [('view_adult_content', 'Can browse and send adult content')]},
        ),
    ]
