# Generated by Django 6.0.8 on 2026-09-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_downloadrequest_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadrequest',
            name='content_type',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
