# Generated by Django 6.0.8 on 2026-09-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_downloadrequest_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadrequest',
            name='notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='downloadrequest',
            name='putio_file_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
